# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.Model_pb2 as Model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\x1a\x0bModel.proto2q\n\x0bInfoService\x12\x1e\n\tFetchInfo\x12\x06.Empty\x1a\x05.Info\"\x00\x30\x01\x12\x1d\n\nUpdateInfo\x12\x05.Info\x1a\x06.Empty\"\x00\x12#\n\x05Offer\x12\x0b.MirrorInfo\x1a\x0b.MirrorInfo\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFOSERVICE']._serialized_start=30
  _globals['_INFOSERVICE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
